### ISSUE TITLE
Dynamic Page Path from API's response attribute

### ISSUE THREAD

**Issue by menepet-wind** [nuxt-community/router-extras-module#119]
If the API responses the pageURL as a part of the JSON, how can we use that to create the page path with this API's data ?
Is it possible to do something like this below ??

```
    ...
  </div>
</template>

<router>
 {
    path: page.pageURL,  // Somehow ??
 }
</router>

<script>
export default {
  name: 'Page',
  async asyncData ({ params, $axios, payload }) {
    if (payload) return { page: payload }
    const page = await $axios.$get(`http://api.mydomain.gr/pages/${params.page}`)
    return { page }
  },
  ...
```

**Comment by farnabaz** [comment]
The short answer is no.  

In nuxt 2 routes will parse and generate on startup and before `asyncData`, this make it impossible to do what you want to do. The possible way is to use [dynamic routes](https://nuxtjs.org/guide/routing/#dynamic-routes) or magical [unknown-dynamic-route](https://nuxtjs.org/guide/routing/#unknown-dynamic-nested-routes)
