### ISSUE TITLE
Alias route whit locale path

### ISSUE THREAD

**Issue by AleeeKoi** [nuxt-community/router-extras-module#131]
Hello!
I'm trying to reuse an existing route simply redefining it's nesting path.
So this is what I have done:

In my existing page that responds to the path `/path1/:id1/path2/:id2`: 
```
<router>
  {
    alias: [
      '/path3/:id1/path4/:id2',
    ]
  }
</router>
```

Compiling it, I can see that the alias is associated in the existing path.. but calling the alias page I get an error 404 (existing page works well).

I'm using also nuxt-i18n module that always prepends the lang code to the url path.

Where I'm wrong? Thank you

**Comment by farnabaz** [comment]
@AleeeKoi Could you provide a reproduction sample on codesandbox?

**Comment by karimennassiri** [comment]
Hello, Can you give us an example how to use this module with i18n
