### ISSUE TITLE
Dynamic Regex in path

### ISSUE THREAD

**Issue by deasurv** [nuxt-community/router-extras-module#132]
Hi. in my project IDs are UUID hash, so I defined related regex for `:id` dynamic parameter in path. something like that:

```
<router lang="js">
  {
    path: '/foo/:id([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})'
  }
</router>

```

but my problem is that I don't want repeat this regex in pages `path` everytime. instead want define the regex once in a const and then import it wherever I need. How could this be possible?

Thanks

**Comment by farnabaz** [comment]
Unfortunately, it is not possible. `router` block does not support variables/import

**Comment by deasurv** [comment]
@farnabaz any chance to have this feature?! or an alternative way?

**Comment by farnabaz** [comment]
You can remove your regex form alias and use Nuxt's [validate method](https://nuxtjs.org/docs/2.x/components-glossary/pages-validate/) to ensure all id is a UUID hash.


I close the issue. But feel free to ask any question or reopen it.
