### ISSUE TITLE
Does it work with Nuxt3?

### ISSUE THREAD

**Issue by RndUsername** [nuxt-community/router-extras-module#164]
Does this module work with Nuxt3, too?
I can't get it to work...

**Comment by RndUsername** [comment]
Alright, I'm a dummy dumm...
Nuxt3 already has [metadata](https://v3.nuxtjs.org/guide/directory-structure/pages#page-metadata) for alias and stuff!

**Comment by elliopitas** [comment]
i wasn't able to get it working for nuxt 3 I get
`Uncaught SyntaxError: import not found: default`
in my browser console when i have the <router> in any page component

I'm trying to enable props for routes by adding
props: true

**Comment by nathanchase** [comment]
I'm finding that the `definePageMeta` `alias` is not working like this module did in Nuxt 2. Specifically, if I have a NuxtLink with a `:to="dynamicRoute"` and I try to replace the `route.params`, it does not work. It acts as if the path is removed entirely.

**Comment by justinkekeocha** [comment]
That is because of this : https://github.com/vuejs/router/blob/main/packages/router/CHANGELOG.md#414-2022-08-22

This module is also based off of vue route

**Comment by harlan-zw** [comment]
Will track Nuxt 3 support here https://github.com/nuxt-community/router-extras-module/issues/171, but I beleive `definePageMeta` should cover most use cases.
