### ISSUE TITLE
Nuxt 3 Support

### ISSUE THREAD

**Issue by harlan-zw** [nuxt-community/router-extras-module#171]
Hi :wave: It looks like this module hasn't been updated for Nuxt 3. In an effort to improve the developer experience of modules, I've updated the module to clarify that it only supports Nuxt 2.

If Nuxt 3 support is added it will be moved to the https://github.com/nuxt-modules organisation.

Alternatives:
- Nuxt core: [definePageMeta](https://nuxt.com/docs/api/utils/define-page-meta#definepagemeta)

@farnabaz Is Nuxt 3 support something you have planned? If not, perhaps we can archive this module?

Please let us know and thanks for your work!

**Comment by Atinux** [comment]
I think we can deprecate it since we have definePageMeta now :)

**Comment by harlan-zw** [comment]
Happy to sort out the deprecation, are we fine just to archive this GitHub repo or is there any other steps you'd like me to take?

**Comment by nathanchase** [comment]
@harlan-zw it might be useful to show examples of how to accomplish all that this modules does with definePageMeta - aliasing, in particular.

**Comment by nathanchase** [comment]
For example, is this possible with definePageMeta?

```
Define custom paths for a page

Simply add a block inside Vue file and define a path in JavaScript or Yaml

JavaScript
<router>
  {
    path: '/posts'
  }
</router>
Yaml
<router>
  path: /posts
</router>
```

**Comment by Atinux** [comment]
You can do:

```vue
<script setup>
definePageMeta({
  path: '/posts'
})
</script>
```

See full API on https://nuxt.com/docs/api/utils/define-page-meta#definepagemeta

**Comment by atinux** [comment]
Updated the readme: https://github.com/nuxt-community/router-extras-module#nuxt-3

**Comment by kalnode** [comment]
Nuxt3's `definePageMeta` works great.

I thought it would be weird having `<router></router>` wrap, while all other technical stuff lived in `<script setup>`.
