### ISSUE TITLE
request support nested routes

### ISSUE THREAD

**Issue by milkmeowo** [nuxt-community/router-extras-module#2]
https://github.com/nuxt-community/router-extras-module/blob/77e31d414d020a04fa85622f3dcc45ddf98fe714/lib/module.js#L10

https://github.com/nuxt-community/router-extras-module/blob/77e31d414d020a04fa85622f3dcc45ddf98fe714/lib/module.js#L46

It seems does not handle the nested routes

when routes has children, does not inject the router-extras

**Comment by farnabaz** [comment]
Hi
Sorry for the late response and thank you for the report, we support nested routes in our next release
