### ISSUE TITLE
Please add documentation for routerNativeAlias (= false)

### ISSUE THREAD

**Issue by farin** [nuxt-community/router-extras-module#25]
routerNativeAlias is still useful option even native aliases exists

vue-router alias only support aliases with equal number or parameters.
Which doesn't cover all cases

Eg. I have one page with optional filters, defined by $route params
page is matched againsts multiple routes
```
/:customer/explore/keywords
/:customer/explore/campaigns/:campaign/keywords
/:customer/explore/campaigns/:campaign/ad-groups/:adGroup/keywords
```
this is not easily possible with default nuxt router. Also aliases don't help here.
But router-extras-module with aliases routerNativeAlias=false works perfectly in this case.
(other options is declare routes manually, but it's pain i want to avoid)

**Comment by farnabaz** [comment]
@farin Thank you for your feedback. I try to improve module docs
also `routerNativeAlias` is not the only way to achieve this, as of v0.1.0 we can define aliases that have its own extras and they create as an individual page(same thing when `routerNativeAlias=false` happens)

In your case:
```
<router>
	path: /:customer/explore/keywords
	alias:
		- 
			path: /:customer/explore/campaigns/:campaign/keywords
		-
			path: /:customer/explore/campaigns/:campaign/ad-groups/:adGroup/keywords

</router>
```
