### ISSUE TITLE
[bug]Not Work with native vue-router router-link

### ISSUE THREAD

**Issue by milkmeowo** [nuxt-community/router-extras-module#5]
https://github.com/nuxt-community/router-extras-module/blob/49a31008a9681675667651fb9c45e9db945c81d7/lib/extras.js#L95-L104

because of `/<router([^>]*)>([\S\s.]*?)<\/router>/`, also work with `<router-link>`
so routerContentMatch get **incorrect** content

example

```js
<template>
  <div>
    <router-link to="path">
      some-path-name
    </router-link>  
  </div>
</template>
<router>
  meta:
    name: foo
</router>
```

> notice: **`<router([^>]*)>`** match `<router-link>` ,or may be `<router-view>`

![image](https://user-images.githubusercontent.com/22437128/53853892-4d26a000-4002-11e9-9f37-c9a0bbb9b6b4.png)

well,yes i can use `nuxt-link` instead of `router-link`,to avoid this bug

but i think should support native vue-router component, right?

**Comment by farnabaz** [comment]
Sure, you're right. We should fix the regex

**Comment by milkmeowo** [comment]
nice!
