### ISSUE TITLE
[Feature request] Supporting JS/JSON

### ISSUE THREAD

**Issue by Atinux** [nuxt-community/router-extras-module#59]
Hi @farnabaz 

Could it be nice to also support `JSON` for the `<router>` block?

I think here we can use a `parse` method that check if the first char is `{` and the last one `}` to parse it as JSON, otherwise fallback to YAML: https://github.com/nuxt-community/router-extras-module/blob/master/lib/extras.js#L88

I have a preference for JSON since most of JavaScript developers knows the syntax and lower the learning curve of this module.

Ideally, supporting JS will be a bonus:

```vue
<router>
{
  name: 'my-name'
}
</router>
```

I believe using a package like [gray-matter](https://github.com/jonschlinkert/gray-matter) for it would be a perfect fit.

Example of supporting JavaScript: https://github.com/jonschlinkert/gray-matter/blob/HEAD/examples/javascript.js

**Comment by Atinux** [comment]
Also, I do believe this module should be used as a `devModules` (not documented yet) to avoid calling it by Nuxt when using `nuxt start` :)

**Comment by farnabaz** [comment]
Hi
I've planned to support javascript from the beginning, but to be honest I was very idealistic for this.  
`grey-matter` is a great package and sure we can use it to support multiple languages
