### ISSUE TITLE
How to enable passing route params as props?

### ISSUE THREAD

**Issue by lobo-tuerto** [nuxt-community/router-extras-module#81]
I'm migrating a Vue CLI app to Nuxt.js and all my router level components are now page components on Nuxt.js.

The problem I'm having is that all router level components accept props based on the route params. Like what's explained here: https://router.vuejs.org/guide/essentials/passing-props.html#boolean-mode

Is there a way to quickly enable this behaviour in Nuxt.js using this module?
I tried installing and adding it to the `buildModules` key, but I was still getting the **Missing required prop** error on my page component.

**Comment by Atinux** [comment]
Could you provide us a reproduction by forking https://template.nuxtjs.org 

Sorry for the late answer
