### ISSUE TITLE
A better name for this module?

### ISSUE THREAD

**Issue by kaceo** [nuxt-community/router-extras-module#89]
First I want to thank you for this module.  It helps tremendously for our project organisation, because we have several hundred pages divided into several teams.  The ability to change the path of each page and aliases outside the file hierarchy helps us keep our sanity.

However I did not understand this module initially, probably because the name is "extra" and that does not immediately ring the bell of what it is and how it is useful.  

Perhaps you want to rename the module to nuxt-router-permalinks or something similar?  That will make the function of assigning a "permalink" to a page more clear, like how we normally use the term in Wordpress or other CMS.

**Comment by farzadso** [comment]
I think Ahad was thinking of a more general module when he started creating it and one of the use cases was being able to change the route. That's why he initially used the word "extras". Although he can tell us his intentions much better @farnabaz

**Comment by farnabaz** [comment]
Although the module widely used for assigning a permalink to a page, this isn't its mission.

Using this module we can modify [constructor options](https://router.vuejs.org/api/#router-construction-options) of page's Route. As you can see there is more to do with constructor options. Define `beforeEnter` guards on the route's configuration object. Provide `props` for the page and define `redirect` option for the page.

look at these examples from my own project.
- Create a standalone alias of the page with custom props
```
<router>
{
    alias: [
        {
            path: '/rooms/a/:slug',
            props: {
                allCities: true
            }
        }
    ]
}
</router>
```

- Provide props for the component if it cames from a specific route
```
<router>
{
    beforeEnter(to, from, next) {
        if (from.name === 'validate-response') {
            to.matched[0].props.sentEvent = true;
        }
        next();
    }
}
</router>
```
- Simply make aliases using capability of VueRouter
```
<router>
    alias:
        - "/:slug([-\\w\\s]+)-list"
        - "/city/:slug([-\\w\\s]+)-list"
</router>
```
