### ISSUE TITLE
EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by aalyokhin** [nuxt-community/router-extras-module#90]
Hi. I'm getting an error which is in subject during build after adding `@nuxtjs/router-extras` to `buildModules`.

Logs - [2020-02-12T19_04_24_306Z-debug.log](https://github.com/nuxt-community/router-extras-module/files/4194503/2020-02-12T19_04_24_306Z-debug.log)

Have already tried to remove `package-lock.json` and reinstalled node modules multiple times. Any help will be much appreciated, thanks in advance!

**Comment by farnabaz** [comment]
I have no idea what can cause this issue. The module just read components in `pages` directory and process them. Try using the module in a clean project.
Creating a sample project to reproduce the issue would be helpful

**Comment by Trixpua** [comment]
Same error here, solved making the downgrade to v1.0.0

**Comment by Atinux** [comment]
Please create a reproduction sandbox or repo and re-open it please :)

**Comment by farnabaz** [comment]
@aalyokhin I close this issue because of inactivity, fill free to reopen issue or ank any questions.
