### ISSUE TITLE
Is it possible to use this to somehow rename the index.vue (homepage, "/") file to something else?

### ISSUE THREAD

**Issue by adrianocr** [nuxt-community/router-extras-module#91]
I'm working on a project with a weird requirement: the gallery of projects is titled "index" and the slug needs to be `/index`. But obviously there's a `index.vue` file in the /pages directory that corresponds to the `/` route.

So I'm trying to find a solution where I can maybe rename the index.vue file to home.vue or something _or_ where I can create a projects.vue file and have the slug `/index` map over to said projects.vue file.

**Comment by farnabaz** [comment]
Sure it's possible, Take a look at `example/pages/home.vue` and `example/pages/galley-index.vue` in following project 
https://codesandbox.io/s/late-tdd-xnlqh
