### ISSUE TITLE
Custom path does not work for dynamic routes on  for generated sites

### ISSUE THREAD

**Issue by sqram** [nuxt-community/router-extras-module#93]
Having `<router>...</router>` inside `pages/foo/bar/_.vue`  causes error when running `nuxt generate`

Repo showcasing issue with minimal files: https://github.com/sqram/router-extended-example

**Comment by farnabaz** [comment]
The problem is you want to generate `/products/chairs/bench`, but there isn't any route with this path
https://github.com/sqram/router-extended-example/blob/master/nuxt.config.js#L43-L47
Change `/products/chairs/bench` to `/products/bench` and it works fine

**Comment by sqram** [comment]
@farnabaz  thanks for that. but how does nuxt know that the route `/products/bench` (and its payload, if any) is to be rendered by product `/products/chairs/_.vue` ?

**Comment by farnabaz** [comment]
It's not magic, `router-extras` changes route definition of a single page.
By default nuxt uses directory structure to create routes, but `router-extras` override generated routes and changes them to whatever you like
